# Subscription data

In [2]:
from vab_rt_import.source import get_data
df = get_data()

In [3]:
df

,id,cognome_socio,nome_socio,num_tessera,num_tessera_associazione,lettera_id_regione_vab,flag_socio,flag_volontario,socio_inattivo,qualifica_socio,...,flag_stampa_ok,flag_stampa_dataora,flag_stampa_id_op,auth_lavori_sede,porta,attivazione_rt_2020,attivazione_locale_2020,da_vaccinare_covid19,data_cambio_password,blocca_account_cambio_password
0,5,Polverini,Andreao,8248,0,T,on,on,0,2,...,,0000-00-00 00:00:00,0,,on,,,,2026-01-03 10:54:32,0
1,7,Magazzini,Nicola,5677,0,T,on,on,1,1,...,,0000-00-00 00:00:00,0,,,,,,0000-00-00 00:00:00,0
2,8,Olivari,Pier Riccardo,6210,0,T,on,on,1,1,...,,0000-00-00 00:00:00,0,,,0,0,0,0000-00-00 00:00:00,0
3,11,Valdettari,Riccardo,7614,0,T,on,on,1,3,...,,0000-00-00 00:00:00,0,,,,,,0000-00-00 00:00:00,0
4,13,Burroni,Maurizio,7389,0,T,on,on,0,1,...,,0000-00-00 00:00:00,0,,,,,,0000-00-00 00:00:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9326,9698,Curella,Matteo,,0,T,,,0,2,...,,0000-00-00 00:00:00,0,,,,,,0000-00-00 00:00:00,0
9327,9699,Bianchi,Andrea,,0,T,on,on,0,1,...,,0000-00-00 00:00:00,0,on,,,,,0000-00-00 00:00:00,0
9328,9700,Ugolini,Dimitri,,0,T,,,0,1,...,,0000-00-00 00:00:00,0,,,,,,0000-00-00 00:00:00,0
9329,9701,Capocaccia,Matteo,,0,T,,on,0,9,...,,0000-00-00 00:00:00,0,,,,,,0000-00-00 00:00:00,0
9330,9702,Masullo,Claudio,,0,T,on,on,0,1,...,,0000-00-00 00:00:00,0,,,,,,0000-00-00 00:00:00,0

In [3]:
list(df.columns)

['id',
 'cognome_socio',
 'nome_socio',
 'num_tessera',
 'num_tessera_associazione',
 'lettera_id_regione_vab',
 'flag_socio',
 'flag_volontario',
 'socio_inattivo',
 'qualifica_socio',
 'data_disattivazione_socio',
 'note_disattivazione_socio',
 'carica_socio',
 'data_iscriz',
 'data_registr_libro_soci',
 'rinnovo_tessera',
 'nato_a',
 'nato_il',
 'cod_fisc',
 'sesso_socio',
 'id_sesso_socio',
 'residente_a',
 'via',
 'num_civico',
 'cap',
 'provincia',
 'tipo_doc_identita_socio',
 'numero_doc_identita_socio',
 'scadenza_doc_identita_socio',
 'doc_identita_socio_rilasc_da',
 'tel_abit',
 'tel_cellulare',
 'tel_altro',
 'email',
 'flag_attivita_antincendio',
 'flag_attivita_protciv',
 'flag_attivita_ecologiche',
 'flag_attivita_logistiche',
 'flag_attivita_altro',
 'nome_azienda',
 'indirizzo_azienda',
 'cap_azienda',
 'comune_azienda',
 'prov_azienda',
 'tel_azienda',
 'fax_azienda',
 'email_azienda',
 'pec_azienda',
 'patente_tipo',
 'patente_numero',
 'pat_rilasc_il',
 'pat_rilasc_da',
 'pat_scad',
 'tessera_pc_olma',
 'sigla_radio',
 'conc_radio',
 'gruppo_sanguigno',
 'scad_antitetanica',
 'antitetanica',
 'allergie_e_patologie',
 'donatore',
 'autocertif',
 'cert_medico',
 'scadenza_visita_medica',
 'idoneita_medica_socio',
 'professione',
 'caratt_lavorative',
 'altra_formazione_esterna',
 'note',
 'taglia_piede',
 'taglia_vest',
 'taglia_guanti',
 'taglia_elmetto',
 'rif_foto',
 'id_sezione_vab',
 'password',
 'access_anagr_globali',
 'access_interv',
 'access_amm',
 'access_anagr_mezzi',
 'access_anagr_soci',
 'access_anagr_varie',
 'access_totale',
 'access_sanitario',
 'access_assicurazioni',
 'access_formazione',
 'access_bacheca_sez_emergenze',
 'access_bacheca_sez_servizi',
 'try',
 'access_time',
 'id_operatore_ins',
 'data_operatore_ins',
 'id_operatore_variaz',
 'data_operatore_variaz',
 'abilitazione_socio_segreteria',
 'abilitazione_socio_presidente',
 'abilitazione_socio_presidente_dataora',
 'abilitazione_socio_presidente_id_op',
 'access_stampa_schede_iscrizione',
 'password_mai_cambiata',
 'brevetti',
 'titstudio',
 'app_altre_ass',
 'hobby_sport',
 'socio_presentatore',
 'num_tessera_socio_presentatore',
 'badge',
 'badge2',
 'id_ingresso_porta_sede',
 'flag_stampa_ok',
 'flag_stampa_dataora',
 'flag_stampa_id_op',
 'auth_lavori_sede',
 'porta',
 'attivazione_rt_2020',
 'attivazione_locale_2020',
 'da_vaccinare_covid19',
 'data_cambio_password',
 'blocca_account_cambio_password']

In [5]:
COLUMNS_TO_PROCESS = [
    'id', # ok
    'num_tessera', # ok
    'num_tessera_associazione', # trash
    'flag_socio', # ok
    'flag_volontario', # ok
    'socio_inattivo', # ok, ma invertito
    'data_disattivazione_socio', # ok
    'note_disattivazione_socio', # trash
    'data_iscriz', # ok
    'data_registr_libro_soci', # ok
    'rinnovo_tessera', # trash
    'socio_presentatore', # trash
    'num_tessera_socio_presentatore', # ok
]
df[COLUMNS_TO_PROCESS]

,id,num_tessera,num_tessera_associazione,flag_socio,flag_volontario,socio_inattivo,data_disattivazione_socio,note_disattivazione_socio,data_iscriz,data_registr_libro_soci,rinnovo_tessera,socio_presentatore,num_tessera_socio_presentatore
0,5,8248,0,on,on,0,0000-00-00,prova 2\r\nprova \r\n,2004-01-01,2004-01-01,0000-00-00,laffi niccolo,3817
1,7,5677,0,on,on,1,0000-00-00,,1996-12-04,0000-00-00,0000-00-00,,
2,8,6210,0,on,on,1,0000-00-00,,0000-00-00,0000-00-00,0000-00-00,,
3,11,7614,0,on,on,1,0000-00-00,,2002-01-01,0000-00-00,0000-00-00,,
4,13,7389,0,on,on,0,0000-00-00,,2001-07-06,0000-00-00,0000-00-00,**,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9326,9698,,0,,,0,0000-00-00,,2026-01-28,0000-00-00,0000-00-00,BAZZICALUPI FILIPPO,
9327,9699,,0,on,on,0,0000-00-00,,2026-01-28,0000-00-00,0000-00-00,,
9328,9700,,0,,,0,0000-00-00,,2026-01-29,0000-00-00,0000-00-00,,
9329,9701,,0,,on,0,0000-00-00,,2026-01-29,0000-00-00,0000-00-00,Vilmo Martinelli,
9330,9702,,0,on,on,0,0000-00-00,,2026-01-30,0000-00-00,0000-00-00,,

In [6]:
df = df[COLUMNS_TO_PROCESS]

In [9]:
df['num_tessera'].unique().shape

(8785,)

In [12]:
df['flag_socio'].value_counts()

flag_socio
on    9214
       117
Name: count, dtype: int64

In [13]:
df['flag_volontario'].value_counts()

flag_volontario
on    9209
       122
Name: count, dtype: int64

In [18]:
df['num_tessera_associazione'].value_counts()
# ok skip

num_tessera_associazione
0    9331
Name: count, dtype: int64

In [19]:
df['socio_inattivo'].value_counts()

socio_inattivo
1    6586
0    2745
Name: count, dtype: int64

In [22]:
df['data_disattivazione_socio'].value_counts()

data_disattivazione_socio
0000-00-00    9157
2025-12-31      94
2025-01-31      26
2024-12-31      19
2025-02-11      18
2025-10-19       4
2025-11-09       3
2024-11-02       1
2025-09-08       1
2025-09-28       1
2025-01-02       1
2024-11-30       1
2024-02-11       1
2025-12-05       1
2025-06-04       1
2025-05-22       1
2025-09-02       1
Name: count, dtype: int64

In [24]:
df['rinnovo_tessera'].value_counts()

rinnovo_tessera
0000-00-00    9327
1900-12-31       4
Name: count, dtype: int64

In [ ]:
# 'rinnovo_tessera' is trash

In [25]:
df[['socio_presentatore',
    'num_tessera_socio_presentatore']].value_counts()

socio_presentatore   num_tessera_socio_presentatore
                                                       5106
.                                                        94
                     3817                                92
ENRICO MANCINI       6347                                82
Martinelli Vilmo     10084                               66
                                                       ...
Letizia Lombardo     14495                                1
Russo Giuseppe       6179                                 1
Mattei Samuele       14012                                1
BAZZICALUPI FILIPPO                                       1
Vilmo Martinelli                                          1
Name: count, Length: 1371, dtype: int64

In [35]:
df[df['num_tessera'].duplicated(keep=False)][['num_tessera', 'cognome_socio', 'nome_socio']].value_counts().to_csv('duplicati.csv')

In [54]:
tessere_multiple = (
    df.groupby('num_tessera')['nome_socio']
      .nunique()
      .gt(1)
)

tessere_problematiche = tessere_multiple[tessere_multiple].index
tessere_problematiche = tessere_problematiche.map(lambda x: None if not x or len(str(x)) < 2 else x)
tessere_problematiche = tessere_problematiche.dropna()

In [56]:
df[df['num_tessera'].isin(tessere_problematiche)][["num_tessera", "nome_socio", "cognome_socio"]].sort_values(['num_tessera', 'nome_socio', 'cognome_socio']).to_csv("duplicati.csv")

In [58]:
df['rinnovo_tessera'].value_counts()

rinnovo_tessera
0000-00-00    9327
1900-12-31       4
Name: count, dtype: int64