In [ ]:
from vab_rt_import.source import get_data
df = get_data()

In [ ]:
from vab_rt_import.process.address import process

In [3]:
df = process(df)

In [4]:
df

,address_country,address_province,address_comune,address_cap,address_street,address_civico,address_phone_home,address_phone_mobile,address_phone_other
0,Italia,Firenze,Calenzano,50041,di leccio,37,NaN,3356668495,NaN
1,Italia,Pistoia,Quarrata,51038,statale,336,NaN,3292805145,NaN
2,Italia,Viterbo,Onano,NaN,NaN,NaN,NaN,3357726884,NaN
3,Italia,Massa-Carrara,Carrara,54031,campo d'appio,55,NaN,3478704922,NaN
4,Italia,Torino,Montanaro,52044,montanare,59/a,0575631246,3356438098,3469443424
...,...,...,...,...,...,...,...,...,...
9326,Italia,Firenze,Empoli,NaN,via del praticcio,NaN,NaN,NaN,NaN
9327,Italia,Grosseto,Follonica,58022,podere sontrone,71/a,NaN,3793273020,NaN
9328,Italia,Prato,Poggio a Caiano,NaN,via aiaccia,16,NaN,3929192521,NaN
9329,Mali,NaN,NaN,NaN,nave,16,NaN,3926284310,NaN
9330,Italia,Firenze,Firenze,NaN,via c.menotti,23,NaN,3755411456,NaN

In [5]:
df[df['address_comune'] == 'Massa e Cozzile']

,address_country,address_province,address_comune,address_cap,address_street,address_civico,address_phone_home,address_phone_mobile,address_phone_other
511,Italia,Pistoia,Massa e Cozzile,51010,via vacchereccia,15,057271723,3402980032,NaN
1691,Italia,Pistoia,Massa e Cozzile,51010,via i maggio,263,0572767940,3298535065,0572771221
1952,Italia,Pistoia,Massa e Cozzile,51010,calamandrei,33,NaN,3403653289,3453965799
1953,Italia,Pistoia,Massa e Cozzile,51010,calamandrei,33,NaN,3484005310,NaN
2363,Italia,Pistoia,Massa e Cozzile,51010,del tenente,NaN,057260292,3289026673,NaN
...,...,...,...,...,...,...,...,...,...
8718,Italia,Pistoia,Massa e Cozzile,NaN,provinciale colligiana,NaN,NaN,3446761408,NaN
8745,Italia,Pistoia,Massa e Cozzile,NaN,via nenni,1/b,NaN,3382727107,NaN
8942,Italia,Pistoia,Massa e Cozzile,NaN,provinciale colligiana,32,NaN,3318814679,NaN
9239,Italia,Pistoia,Massa e Cozzile,NaN,via vetriano,102,NaN,3391949736,NaN
9240,Italia,Pistoia,Massa e Cozzile,NaN,via vetriano,102,NaN,NaN,NaN