# Subscription Data

In [1]:
from vab_rt_import.utils import get_data
df = get_data()

In [2]:
from vab_rt_import.process.process_subscription import process_subscription

In [3]:
df = process_subscription(df)

N_tessera 3293. not recognized.
N_tessera LO01 not recognized.
N_tessera 65535 too large.
N_tessera 9291. not recognized.
N_tessera 99997 too large.
N_tessera 99999 too large.
N_tessera 99990 too large.
N_tessera LO02 not recognized.
N_tessera CA2 not recognized.
N_tessera ORT01 not recognized.
N_tessera sc001 not recognized.
N_tessera sc003 not recognized.
N_tessera sc002 not recognized.
N_tessera a002 not recognized.
N_tessera .... not recognized.
N_tessera .... not recognized.
N_tessera PU01 not recognized.
N_tessera CA01 not recognized.
N_tessera sc011 not recognized.
N_tessera sc012 not recognized.
N_tessera sc013 not recognized.
N_tessera sc014 not recognized.
N_tessera sc015 not recognized.
N_tessera comfi not recognized.
N_tessera sc016 not recognized.
N_tessera E01 not recognized.
N_tessera 99991 too large.
N_tessera 40000 too large.
N_tessera 99000 too large.
N_tessera 99011 too large.
N_tessera 99012 too large.
N_tessera SA3 not recognized.
N_tessera sa3 not recognized.
N_tessera sa4 not recognized.
N_tessera sa5 not recognized.
N_tessera sa16 not recognized.
N_tessera sa6 not recognized.
N_tessera sar2 not recognized.
N_tessera sa8 not recognized.
N_tessera sa95 not recognized.
N_tessera sa80 not recognized.
N_tessera sa50 not recognized.
N_tessera sa43 not recognized.
N_tessera sa51 not recognized.
N_tessera sa82 not recognized.
N_tessera sa47 not recognized.
N_tessera sa48 not recognized.
N_tessera sa29 not recognized.
N_tessera sa10 not recognized.
N_tessera sa11 not recognized.
N_tessera sa38 not recognized.
N_tessera sa40 not recognized.
N_tessera sa53 not recognized.
N_tessera sa67 not recognized.
N_tessera sa42 not recognized.
N_tessera sa46 not recognized.
N_tessera sa41 not recognized.
N_tessera sa52 not recognized.
N_tessera sa74 not recognized.
N_tessera sa68 not recognized.
N_tessera sa62 not recognized.
N_tessera sa61 not recognized.
N_tessera sa65 not recognized.
N_tessera sa72 not recognized.
N_tessera sa81 not recognized.
N_tessera sa54 not recognized.
N_tessera sa63 not recognized.
N_tessera sa78 not recognized.
N_tessera sa76 not recognized.
N_tessera sa73 not recognized.
N_tessera sa64 not recognized.
N_tessera sa71 not recognized.
N_tessera Sa88 not recognized.
N_tessera sa57 not recognized.
N_tessera sa56 not recognized.
N_tessera sa70 not recognized.
N_tessera sa45 not recognized.
N_tessera sa75 not recognized.
N_tessera sa84 not recognized.
N_tessera sa39 not recognized.
N_tessera sa44 not recognized.
N_tessera sa100 not recognized.
N_tessera sa101 not recognized.
N_tessera sa98 not recognized.
N_tessera sa93 not recognized.
N_tessera sa99 not recognized.
N_tessera sa20 not recognized.
N_tessera sa9 not recognized.
N_tessera sa12 not recognized.
N_tessera sa13 not recognized.
N_tessera sa14 not recognized.
N_tessera sa15 not recognized.
N_tessera sa18 not recognized.
N_tessera sa17 not recognized.
N_tessera sa21 not recognized.
N_tessera sa23 not recognized.
N_tessera sa22 not recognized.
N_tessera sa24 not recognized.
N_tessera sa25 not recognized.
N_tessera sa19 not recognized.
N_tessera sa49 not recognized.
N_tessera sa26 not recognized.
N_tessera sa30 not recognized.
N_tessera sa90 not recognized.
N_tessera sa34 not recognized.
N_tessera sa31 not recognized.
N_tessera sa102 not recognized.
N_tessera sa79 not recognized.
N_tessera sa37 not recognized.
N_tessera sa36 not recognized.
N_tessera sa87 not recognized.
N_tessera sa27 not recognized.
N_tessera sa85 not recognized.
N_tessera sa28 not recognized.
N_tessera sa32 not recognized.
N_tessera sa33 not recognized.
N_tessera sa35 not recognized.
N_tessera sa91 not recognized.
N_tessera sa92 not recognized.
N_tessera sa89 not recognized.
N_tessera sa66 not recognized.
N_tessera sa86 not recognized.
N_tessera sa94 not recognized.
N_tessera sa55 not recognized.
N_tessera sa59 not recognized.
N_tessera sa58 not recognized.
N_tessera sa69 not recognized.
N_tessera sa77 not recognized.
N_tessera sa60 not recognized.
N_tessera sa83 not recognized.
N_tessera sa96 not recognized.
N_tessera sa97 not recognized.
N_tessera PU03 not recognized.
N_tessera A01 not recognized.
N_tessera E02 not recognized.
N_tessera PU002 not recognized.
N_tessera E03 not recognized.
N_tessera E04 not recognized.
N_tessera E05 not recognized.
N_tessera E06 not recognized.
N_tessera E07 not recognized.
N_tessera E08 not recognized.
N_tessera E09 not recognized.
N_tessera E10 not recognized.
N_tessera E11 not recognized.
N_tessera E12 not recognized.
N_tessera E13 not recognized.
N_tessera E14 not recognized.
N_tessera E15 not recognized.
N_tessera E16 not recognized.
N_tessera E17 not recognized.
N_tessera E18 not recognized.
N_tessera e19 not recognized.
N_tessera E20 not recognized.
N_tessera E21 not recognized.
N_tessera E22 not recognized.
N_tessera E23 not recognized.
N_tessera E24 not recognized.
N_tessera e25 not recognized.
N_tessera e26 not recognized.
N_tessera e27 not recognized.
N_tessera e28 not recognized.
N_tessera e28 not recognized.
N_tessera e29 not recognized.
N_tessera 100000 too large.
N_tessera 100001 too large.
N_tessera 100002 too large.
N_tessera 100004 too large.
N_tessera 100005 too large.
N_tessera 118118 too large.
N_tessera 99998 too large.
N_tessera ca03 not recognized.
N_tessera LA01 not recognized.
N_tessera 99999 too large.
N_tessera LA1 not recognized.
N_tessera 99999 too large.
N_tessera D1 not recognized.
N_tessera 99013 too large.
N_tessera 58445 too large.
N_tessera X not recognized.
N_tessera 10404T not recognized.
N_tessera 10662T not recognized.
N_tessera 10681T not recognized.
N_tessera 10662T not recognized.
N_tessera 10404T not recognized.
N_tessera 10946T not recognized.
N_tessera 10662T not recognized.
N_tessera 11934T not recognized.
N_tessera 10662T not recognized.
N_tessera 10662T not recognized.
N_tessera 5498T not recognized.
N_tessera 6677T not recognized.
N_tessera 12221T not recognized.
N_tessera 12891T not recognized.
N_tessera 12891T not recognized.
N_tessera 12452T not recognized.
N_tessera 8737 T not recognized.
N_tessera 8737T not recognized.
N_tessera 12063T not recognized.
N_tessera 12284T not recognized.
N_tessera 10629t not recognized.
N_tessera 11270T not recognized.
N_tessera 11270T not recognized.
N_tessera 11270T not recognized.
N_tessera 11270T not recognized.
N_tessera 11270T not recognized.
N_tessera 6298T not recognized.
N_tessera 10716T not recognized.
N_tessera 10716T not recognized.
N_tessera 10716T not recognized.
N_tessera 11270T not recognized.
N_tessera 11270T not recognized.
N_tessera 12893T not recognized.
N_tessera 10107T not recognized.
N_tessera 10107T not recognized.
N_tessera 7668T not recognized.
N_tessera 12063T not recognized.
N_tessera 12891T not recognized.
N_tessera 12063T not recognized.
N_tessera 12063T not recognized.
N_tessera 12891T not recognized.
N_tessera 12891T not recognized.
N_tessera 12063T not recognized.
N_tessera 110556 too large.
N_tessera 12417T not recognized.
N_tessera 7668T not recognized.
N_tessera 14569T not recognized.
N_tessera 14611T not recognized.
N_tessera 10118T not recognized.
N_tessera 14611T not recognized.
N_tessera 13397T not recognized.
N_tessera 13373T not recognized.
N_tessera 11091T not recognized.
N_tessera 9062T not recognized.
N_tessera 8734t not recognized.

In [4]:
df

,id,n_tessera,new_n_tessera,socio,volontario,active,start_date,start_date_effective,end_date,referring_member
0,5,8248,False,True,True,True,2004-01-01,2004-01-01,NaT,<NA>
50,67,3065,False,True,True,True,1996-02-18,NaT,NaT,<NA>
59,76,3574,False,True,True,False,1996-02-01,NaT,2024-12-31,<NA>
62,79,3648,False,True,True,False,1996-02-07,NaT,2024-12-31,<NA>
106,123,4757,False,True,True,True,1992-02-03,1992-02-03,NaT,<NA>
...,...,...,...,...,...,...,...,...,...,...
9310,9682,17040,False,True,True,True,2026-01-18,2026-01-24,NaT,<NA>
9312,9684,17042,False,True,True,True,2026-01-20,2026-01-24,NaT,<NA>
9313,9685,17018,False,False,False,True,2026-01-21,2026-01-24,NaT,<NA>
9314,9686,17022,False,True,True,True,2026-01-21,2026-01-24,NaT,7482
9322,9694,17021,False,True,True,True,2026-01-24,2026-01-24,NaT,<NA>

In [5]:
EXPORT_FILE = "../../process/data/proprocessed_subscription_data"

In [6]:
df.to_csv(EXPORT_FILE + ".csv", index=True)
df.to_parquet(EXPORT_FILE + ".parquet")

# Importing

In [17]:
EXPORT_FILE = "../../process/data/proprocessed_subscription_data"

In [18]:
import pandas as pd

In [19]:
df = pd.read_parquet(EXPORT_FILE + ".parquet")
df

,id,n_tessera,new_n_tessera,socio,volontario,active,start_date,start_date_effective,end_date,referring_member
0,5,8248,False,True,True,True,2004-01-01,2004-01-01,NaT,<NA>
50,67,3065,False,True,True,True,1996-02-18,NaT,NaT,<NA>
59,76,3574,False,True,True,False,1996-02-01,NaT,2024-12-31,<NA>
62,79,3648,False,True,True,False,1996-02-07,NaT,2024-12-31,<NA>
106,123,4757,False,True,True,True,1992-02-03,1992-02-03,NaT,<NA>
...,...,...,...,...,...,...,...,...,...,...
9310,9682,17040,False,True,True,True,2026-01-18,2026-01-24,NaT,<NA>
9312,9684,17042,False,True,True,True,2026-01-20,2026-01-24,NaT,<NA>
9313,9685,17018,False,False,False,True,2026-01-21,2026-01-24,NaT,<NA>
9314,9686,17022,False,True,True,True,2026-01-21,2026-01-24,NaT,7482
9322,9694,17021,False,True,True,True,2026-01-24,2026-01-24,NaT,<NA>

In [10]:
from vab_rt_import.importing.utils.auth import get_client
client = get_client()

In [11]:
from vab_rt_import.importing import import_entity

In [12]:
import_entity(df, client)

Skipping row 1161 due to invalid lookup
Skipping row 1529 due to invalid lookup
Skipping row 2778 due to invalid lookup
Skipping row 3266 due to invalid lookup
Skipping row 3961 due to invalid lookup
Skipping row 4825 due to invalid lookup
Skipping row 5125 due to invalid lookup
Skipping row 5436 due to invalid lookup
Skipping row 5587 due to invalid lookup
Skipping row 5676 due to invalid lookup
Skipping row 5772 due to invalid lookup
Skipping row 5811 due to invalid lookup
Skipping row 6143 due to invalid lookup
Skipping row 6159 due to invalid lookup
Skipping row 6188 due to invalid lookup
Skipping row 6189 due to invalid lookup
Skipping row 6248 due to invalid lookup
Skipping row 6257 due to invalid lookup
Skipping row 6259 due to invalid lookup
Skipping row 6262 due to invalid lookup
Skipping row 6271 due to invalid lookup
Skipping row 6317 due to invalid lookup
Skipping row 6323 due to invalid lookup
Skipping row 6350 due to invalid lookup
Skipping row 6383 due to invalid lookup
Skipping row 6477 due to invalid lookup
Skipping row 6492 due to invalid lookup
Skipping row 6494 due to invalid lookup
Skipping row 6531 due to invalid lookup
Skipping row 6532 due to invalid lookup
Skipping row 6564 due to invalid lookup
Skipping row 6595 due to invalid lookup
Skipping row 6626 due to invalid lookup
Skipping row 6661 due to invalid lookup
Skipping row 6679 due to invalid lookup
Skipping row 6735 due to invalid lookup
Skipping row 6737 due to invalid lookup
Skipping row 6842 due to invalid lookup
Skipping row 6848 due to invalid lookup
Skipping row 6850 due to invalid lookup
Skipping row 6851 due to invalid lookup
Skipping row 6864 due to invalid lookup
Skipping row 6883 due to invalid lookup
Skipping row 6935 due to invalid lookup
Skipping row 6953 due to invalid lookup
Skipping row 6955 due to invalid lookup
Skipping row 6974 due to invalid lookup
Skipping row 6977 due to invalid lookup
Skipping row 7041 due to invalid lookup
Skipping row 7056 due to invalid lookup
Skipping row 7057 due to invalid lookup
Skipping row 7058 due to invalid lookup
Skipping row 7071 due to invalid lookup
Skipping row 7107 due to invalid lookup
Skipping row 7140 due to invalid lookup
Skipping row 7147 due to invalid lookup
Skipping row 7166 due to invalid lookup
Skipping row 7172 due to invalid lookup
Skipping row 7175 due to invalid lookup
Skipping row 7195 due to invalid lookup
Skipping row 7196 due to invalid lookup
Skipping row 7235 due to invalid lookup
Skipping row 7296 due to invalid lookup
Skipping row 7310 due to invalid lookup
Skipping row 7318 due to invalid lookup
Skipping row 7319 due to invalid lookup
Skipping row 7382 due to invalid lookup
Skipping row 7438 due to invalid lookup
Skipping row 7500 due to invalid lookup
Skipping row 7501 due to invalid lookup
Skipping row 7522 due to invalid lookup
Skipping row 7530 due to invalid lookup
Skipping row 7537 due to invalid lookup
Skipping row 7582 due to invalid lookup
Skipping row 7588 due to invalid lookup
Skipping row 7617 due to invalid lookup
Skipping row 7628 due to invalid lookup
Skipping row 7659 due to invalid lookup
Skipping row 7666 due to invalid lookup
Skipping row 7670 due to invalid lookup
Skipping row 7698 due to invalid lookup
Skipping row 7713 due to invalid lookup
Skipping row 7714 due to invalid lookup
Skipping row 7715 due to invalid lookup
Skipping row 7716 due to invalid lookup
Skipping row 7717 due to invalid lookup
Skipping row 7719 due to invalid lookup
Skipping row 7720 due to invalid lookup
Skipping row 7722 due to invalid lookup
Skipping row 7725 due to invalid lookup
Skipping row 7730 due to invalid lookup
Skipping row 7752 due to invalid lookup
Skipping row 7815 due to invalid lookup
Skipping row 7820 due to invalid lookup
Skipping row 7837 due to invalid lookup
Skipping row 7853 due to invalid lookup
Skipping row 7871 due to invalid lookup
Skipping row 7919 due to invalid lookup
Skipping row 7926 due to invalid lookup
Skipping row 7941 due to invalid lookup
Skipping row 7945 due to invalid lookup
Skipping row 7946 due to invalid lookup
Skipping row 7958 due to invalid lookup
Skipping row 7959 due to invalid lookup
Skipping row 7966 due to invalid lookup
Skipping row 7985 due to invalid lookup
Skipping row 7997 due to invalid lookup
Skipping row 7999 due to invalid lookup
Skipping row 8009 due to invalid lookup
Skipping row 8012 due to invalid lookup
Skipping row 8039 due to invalid lookup
Skipping row 8046 due to invalid lookup
Skipping row 8082 due to invalid lookup
Skipping row 8095 due to invalid lookup
Skipping row 8188 due to invalid lookup
Skipping row 8189 due to invalid lookup
Skipping row 8262 due to invalid lookup
Skipping row 8307 due to invalid lookup
Skipping row 8324 due to invalid lookup
Skipping row 8347 due to invalid lookup
Skipping row 8351 due to invalid lookup
Skipping row 8353 due to invalid lookup
Skipping row 8374 due to invalid lookup
Skipping row 8405 due to invalid lookup
Skipping row 8413 due to invalid lookup
Skipping row 8475 due to invalid lookup
Skipping row 8524 due to invalid lookup
Skipping row 8525 due to invalid lookup
Skipping row 8534 due to invalid lookup
Skipping row 8544 due to invalid lookup
Skipping row 8551 due to invalid lookup
Skipping row 8557 due to invalid lookup
Skipping row 8558 due to invalid lookup
Skipping row 8571 due to invalid lookup
Skipping row 8576 due to invalid lookup
Skipping row 8585 due to invalid lookup
Skipping row 8600 due to invalid lookup
Skipping row 8601 due to invalid lookup
Skipping row 8603 due to invalid lookup
Skipping row 8668 due to invalid lookup
Skipping row 8671 due to invalid lookup
Skipping row 8688 due to invalid lookup
Skipping row 8693 due to invalid lookup
Skipping row 8706 due to invalid lookup
Skipping row 8709 due to invalid lookup
Skipping row 8725 due to invalid lookup
Skipping row 8743 due to invalid lookup
Skipping row 8748 due to invalid lookup
Skipping row 8781 due to invalid lookup
Skipping row 8782 due to invalid lookup
Skipping row 8783 due to invalid lookup
Skipping row 8795 due to invalid lookup
Skipping row 8797 due to invalid lookup
Skipping row 8806 due to invalid lookup
Skipping row 8807 due to invalid lookup
Skipping row 8813 due to invalid lookup
Skipping row 8818 due to invalid lookup
Skipping row 8819 due to invalid lookup
Skipping row 8828 due to invalid lookup
Skipping row 8867 due to invalid lookup
Skipping row 8873 due to invalid lookup
Skipping row 8914 due to invalid lookup
Skipping row 8916 due to invalid lookup
Skipping row 8919 due to invalid lookup
Skipping row 8920 due to invalid lookup
Skipping row 8956 due to invalid lookup
Skipping row 8976 due to invalid lookup
Skipping row 8996 due to invalid lookup
Skipping row 9049 due to invalid lookup
Skipping row 9071 due to invalid lookup
Skipping row 9076 due to invalid lookup
Skipping row 9078 due to invalid lookup
Skipping row 9090 due to invalid lookup
Skipping row 9091 due to invalid lookup
Skipping row 9093 due to invalid lookup
Skipping row 9094 due to invalid lookup
Skipping row 9104 due to invalid lookup
Skipping row 9114 due to invalid lookup
Skipping row 9137 due to invalid lookup
Skipping row 9143 due to invalid lookup
Skipping row 9144 due to invalid lookup
Skipping row 9145 due to invalid lookup
Skipping row 9148 due to invalid lookup
Skipping row 9150 due to invalid lookup
Skipping row 9157 due to invalid lookup
Skipping row 9162 due to invalid lookup
Skipping row 9165 due to invalid lookup
Skipping row 9167 due to invalid lookup
Skipping row 9168 due to invalid lookup
Skipping row 9172 due to invalid lookup
Skipping row 9176 due to invalid lookup
Skipping row 9178 due to invalid lookup
Skipping row 9194 due to invalid lookup
Skipping row 9199 due to invalid lookup
Skipping row 9208 due to invalid lookup
Skipping row 9213 due to invalid lookup
Skipping row 9270 due to invalid lookup
Skipping row 9293 due to invalid lookup
Skipping row 9305 due to invalid lookup
Skipping row 9306 due to invalid lookup
Skipping row 9309 due to invalid lookup
Skipping row 9313 due to invalid lookup
Skipping row 9314 due to invalid lookup
Skipping row 9315 due to invalid lookup
Skipping row 9325 due to invalid lookup
Skipping row 9333 due to invalid lookup
Skipping row 9339 due to invalid lookup
Skipping row 9344 due to invalid lookup
Skipping row 9352 due to invalid lookup
Skipping row 9353 due to invalid lookup
Skipping row 9383 due to invalid lookup
Skipping row 9430 due to invalid lookup
Skipping row 9432 due to invalid lookup
Skipping row 9433 due to invalid lookup
Skipping row 9442 due to invalid lookup
Skipping row 9448 due to invalid lookup
Skipping row 9461 due to invalid lookup
Skipping row 9462 due to invalid lookup
Skipping row 9463 due to invalid lookup
Skipping row 9465 due to invalid lookup
Skipping row 9473 due to invalid lookup
Skipping row 9492 due to invalid lookup
Skipping row 9513 due to invalid lookup
Skipping row 9526 due to invalid lookup
Skipping row 9532 due to invalid lookup
Skipping row 9533 due to invalid lookup
Skipping row 9534 due to invalid lookup
Skipping row 9535 due to invalid lookup
Skipping row 9551 due to invalid lookup
Skipping row 9559 due to invalid lookup
Skipping row 9565 due to invalid lookup
Skipping row 9569 due to invalid lookup
Skipping row 9603 due to invalid lookup
Skipping row 9611 due to invalid lookup
Skipping row 9615 due to invalid lookup
Skipping row 9637 due to invalid lookup

UnexpectedStatus: Unexpected status code: 500

Response content:
<!doctype html>
<html lang=en>
  <head>
    <title>django.db.utils.IntegrityError: duplicate key value violates unique constraint &#34;subscriptions_subscription_pkey&#34;
DETAIL:  Key (n_tessera)=(8248) already exists.
 // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css">
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script>
      var CONSOLE_MODE = false,
          EVALEX = true,
          EVALEX_TRUSTED = false,
          SECRET = "V7IEFewcde0huL19tgan";
    </script>
  </head>
  <body style="background-color: #fff">
    <div class="debugger">
<h1>django.db.utils.IntegrityError</h1>
<div class="detail">
  <p class="errormsg">django.db.utils.IntegrityError: duplicate key value violates unique constraint &#34;subscriptions_subscription_pkey&#34;
DETAIL:  Key (n_tessera)=(8248) already exists.
</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  <h3></h3>
  <ul><li><div class="frame" id="frame-139874137339392">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/db/backends/utils.py"</cite>,
      line <em class="line">105</em>,
      in <code class="function">_execute</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>with self.db.wrap_database_errors:</pre>
<pre class="line before"><span class="ws">            </span>if params is None:</pre>
<pre class="line before"><span class="ws">                </span># params default might be backend specific.</pre>
<pre class="line before"><span class="ws">                </span>return self.cursor.execute(sql)</pre>
<pre class="line before"><span class="ws">            </span>else:</pre>
<pre class="line current"><span class="ws">                </span>return self.cursor.execute(sql, params)
<span class="ws">                </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def _executemany(self, sql, param_list, *ignored_wrapper_args):</pre>
<pre class="line after"><span class="ws">        </span># Raise a warning during app initialization (stored_app_configs is only</pre>
<pre class="line after"><span class="ws">        </span># ever set during testing).</pre>
<pre class="line after"><span class="ws">        </span>if not apps.ready and not apps.stored_app_configs:</pre></div>
</div>

<li><div class="frame" id="frame-139874139766144">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/psycopg/cursor.py"</cite>,
      line <em class="line">117</em>,
      in <code class="function">execute</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>with self._conn.lock:</pre>
<pre class="line before"><span class="ws">                </span>self._conn.wait(</pre>
<pre class="line before"><span class="ws">                    </span>self._execute_gen(query, params, prepare=prepare, binary=binary)</pre>
<pre class="line before"><span class="ws">                </span>)</pre>
<pre class="line before"><span class="ws">        </span>except e._NO_TRACEBACK as ex:</pre>
<pre class="line current"><span class="ws">            </span>raise ex.with_traceback(None)
<span class="ws">            </span>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>return self</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def executemany(</pre>
<pre class="line after"><span class="ws">        </span>self, query: Query, params_seq: Iterable[Params], *, returning: bool = False</pre>
<pre class="line after"><span class="ws">    </span>) -&gt; None:</pre></div>
</div>

<li><div class="exc-divider">The above exception was the direct cause of the following exception:</div>
<li><div class="frame" id="frame-139874137340992">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/core/handlers/wsgi.py"</cite>,
      line <em class="line">124</em>,
      in <code class="function">__call__</code></h4>
  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>
<pre class="line before"><span class="ws">        </span>set_script_prefix(get_script_name(environ))</pre>
<pre class="line before"><span class="ws">        </span>signals.request_started.send(sender=self.__class__, environ=environ)</pre>
<pre class="line before"><span class="ws">        </span>request = self.request_class(environ)</pre>
<pre class="line current"><span class="ws">        </span>response = self.get_response(request)
<span class="ws">        </span>           ^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>response._handler_class = self.__class__</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>status = &#34;%d %s&#34; % (response.status_code, response.reason_phrase)</pre>
<pre class="line after"><span class="ws">        </span>response_headers = [</pre></div>
</div>

<li><div class="frame" id="frame-139874137328992">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/core/handlers/base.py"</cite>,
      line <em class="line">140</em>,
      in <code class="function">get_response</code></h4>
  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def get_response(self, request):</pre>
<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;Return an HttpResponse object for the given HttpRequest.&#34;&#34;&#34;</pre>
<pre class="line before"><span class="ws">        </span># Setup default url resolver for this thread</pre>
<pre class="line before"><span class="ws">        </span>set_urlconf(settings.ROOT_URLCONF)</pre>
<pre class="line current"><span class="ws">        </span>response = self._middleware_chain(request)
<span class="ws">        </span>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>response._resource_closers.append(request.close)</pre>
<pre class="line after"><span class="ws">        </span>if response.status_code &gt;= 400:</pre>
<pre class="line after"><span class="ws">            </span>log_response(</pre>
<pre class="line after"><span class="ws">                </span>&#34;%s: %s&#34;,</pre>
<pre class="line after"><span class="ws">                </span>response.reason_phrase,</pre></div>
</div>

<li><div class="frame" id="frame-139874396767392">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py"</cite>,
      line <em class="line">57</em>,
      in <code class="function">inner</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">        </span>@wraps(get_response)</pre>
<pre class="line before"><span class="ws">        </span>def inner(request):</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>response = get_response(request)</pre>
<pre class="line before"><span class="ws">            </span>except Exception as exc:</pre>
<pre class="line current"><span class="ws">                </span>response = response_for_exception(request, exc)
<span class="ws">                </span>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">            </span>return response</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>return inner</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-139874137340672">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py"</cite>,
      line <em class="line">141</em>,
      in <code class="function">response_for_exception</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>logger=security_logger,</pre>
<pre class="line before"><span class="ws">        </span>)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>else:</pre>
<pre class="line before"><span class="ws">        </span>signals.got_request_exception.send(sender=None, request=request)</pre>
<pre class="line current"><span class="ws">        </span>response = handle_uncaught_exception(
<span class="ws">        </span>           </pre>
<pre class="line after"><span class="ws">            </span>request, get_resolver(get_urlconf()), sys.exc_info()</pre>
<pre class="line after"><span class="ws">        </span>)</pre>
<pre class="line after"><span class="ws">        </span>log_response(</pre>
<pre class="line after"><span class="ws">            </span>&#34;%s: %s&#34;,</pre>
<pre class="line after"><span class="ws">            </span>response.reason_phrase,</pre></div>
</div>

<li><div class="frame" id="frame-139874137335552">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py"</cite>,
      line <em class="line">182</em>,
      in <code class="function">handle_uncaught_exception</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">    </span>&#34;&#34;&#34;</pre>
<pre class="line before"><span class="ws">    </span>if settings.DEBUG_PROPAGATE_EXCEPTIONS:</pre>
<pre class="line before"><span class="ws">        </span>raise</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>if settings.DEBUG:</pre>
<pre class="line current"><span class="ws">        </span>return debug.technical_500_response(request, *exc_info)
<span class="ws">        </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span># Return an HttpResponse that displays a friendly error message.</pre>
<pre class="line after"><span class="ws">    </span>callback = resolver.resolve_error_handler(500)</pre>
<pre class="line after"><span class="ws">    </span>return callback(request)</pre></div>
</div>

<li><div class="frame" id="frame-139874139755584">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django_extensions/management/technical_response.py"</cite>,
      line <em class="line">41</em>,
      in <code class="function">null_technical_500_response</code></h4>
  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>try:</pre>
<pre class="line before"><span class="ws">        </span>if exc_value is None:</pre>
<pre class="line before"><span class="ws">            </span>exc_value = exc_type()</pre>
<pre class="line before"><span class="ws">        </span>if exc_value.__traceback__ is not tb:</pre>
<pre class="line current"><span class="ws">            </span>raise exc_value.with_traceback(tb)
<span class="ws">            </span>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>raise exc_value</pre>
<pre class="line after"><span class="ws">    </span>finally:</pre>
<pre class="line after"><span class="ws">        </span>exc_value = None</pre>
<pre class="line after"><span class="ws">        </span>tb = None</pre></div>
</div>

<li><div class="frame" id="frame-139874137340512">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py"</cite>,
      line <em class="line">55</em>,
      in <code class="function">inner</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">    </span>else:</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span>@wraps(get_response)</pre>
<pre class="line before"><span class="ws">        </span>def inner(request):</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line current"><span class="ws">                </span>response = get_response(request)
<span class="ws">                </span>           ^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">            </span>except Exception as exc:</pre>
<pre class="line after"><span class="ws">                </span>response = response_for_exception(request, exc)</pre>
<pre class="line after"><span class="ws">            </span>return response</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>return inner</pre></div>
</div>

<li><div class="frame" id="frame-139874139754304">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/core/handlers/base.py"</cite>,
      line <em class="line">197</em>,
      in <code class="function">_get_response</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>wrapped_callback = self.make_view_atomic(callback)</pre>
<pre class="line before"><span class="ws">            </span># If it is an asynchronous view, run it in a subthread.</pre>
<pre class="line before"><span class="ws">            </span>if iscoroutinefunction(wrapped_callback):</pre>
<pre class="line before"><span class="ws">                </span>wrapped_callback = async_to_sync(wrapped_callback)</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line current"><span class="ws">                </span>response = wrapped_callback(request, *callback_args, **callback_kwargs)
<span class="ws">                </span>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">                </span>response = self.process_exception_by_middleware(e, request)</pre>
<pre class="line after"><span class="ws">                </span>if response is None:</pre>
<pre class="line after"><span class="ws">                    </span>raise</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-139874139760704">
  <h4>File <cite class="filename">"/usr/local/lib/python3.13/contextlib.py"</cite>,
      line <em class="line">85</em>,
      in <code class="function">inner</code></h4>
  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def __call__(self, func):</pre>
<pre class="line before"><span class="ws">        </span>@wraps(func)</pre>
<pre class="line before"><span class="ws">        </span>def inner(*args, **kwds):</pre>
<pre class="line before"><span class="ws">            </span>with self._recreate_cm():</pre>
<pre class="line current"><span class="ws">                </span>return func(*args, **kwds)
<span class="ws">                </span>       ^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws">        </span>return inner</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>class AsyncContextDecorator(object):</pre>
<pre class="line after"><span class="ws">    </span>&#34;A base class or mixin that enables async context managers to work as decorators.&#34;</pre></div>
</div>

<li><div class="frame" id="frame-139874139759104">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py"</cite>,
      line <em class="line">65</em>,
      in <code class="function">_view_wrapper</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>return await view_func(request, *args, **kwargs)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>else:</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span>def _view_wrapper(request, *args, **kwargs):</pre>
<pre class="line current"><span class="ws">            </span>return view_func(request, *args, **kwargs)
<span class="ws">            </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>_view_wrapper.csrf_exempt = True</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>return wraps(view_func)(_view_wrapper)</pre></div>
</div>

<li><div class="frame" id="frame-139874139752064">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/django/views/generic/base.py"</cite>,
      line <em class="line">105</em>,
      in <code class="function">view</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">            </span>if not hasattr(self, &#34;request&#34;):</pre>
<pre class="line before"><span class="ws">                </span>raise AttributeError(</pre>
<pre class="line before"><span class="ws">                    </span>&#34;%s instance has no &#39;request&#39; attribute. Did you override &#34;</pre>
<pre class="line before"><span class="ws">                    </span>&#34;setup() and forget to call super()?&#34; % cls.__name__</pre>
<pre class="line before"><span class="ws">                </span>)</pre>
<pre class="line current"><span class="ws">            </span>return self.dispatch(request, *args, **kwargs)
<span class="ws">            </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>view.view_class = cls</pre>
<pre class="line after"><span class="ws">        </span>view.view_initkwargs = initkwargs</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span># __name__ and __qualname__ are intentionally left unchanged as</pre></div>
</div>

<li><div class="frame" id="frame-139874139762144">
  <h4>File <cite class="filename">"/app/.venv/lib/python3.13/site-packages/rest_framework/views.py"</cite>,
      line <em class="line">515</em>,
      in <code class="function">dispatch</code></h4>
  <div class="source library"><pre class="line before"><span class="ws">                </span>handler = self.http_method_not_allowed</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">            </span>response = handler(request, *args, **kwargs)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span>except Exception as exc:</pre>
<pre class="line current"><span class="ws">            </span>response = self.handle_exception(exc)
<span class="ws">            </span>           ^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>self.response = self.finalize_response(request, response, *args, **kwargs)</pre>
<pre class="line after"><span class="ws">        </span>return self.response</pre>